name: container
on:
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: allanoricil/sfdx-cli:v2
    steps:
      - name: Check for dockerenv file
        run: sfdx --version
